Repository Natizyskunk/vscode-sftp, pull requests merged in 2022-11, with the labels that each got.

#221 Add multiple select
  package.json
  src/commands/shared.ts
  src/modules/remoteExplorer/explorer.ts
Labels: Hacktoberfest, hacktoberfest-accepted

#253 Bumped version to v1.16.1
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/commands/shared.ts
  src/modules/remoteExplorer/explorer.ts
Labels: documentation, enhancement

#271 [#249] Fix case rename
  src/modules/fileActivityMonitor.ts
Labels: bug, important

#272 [#249] Fix case rename
  package-lock.json
  package.json
Labels: bug, important
